export const TIME_ACCESS_TOKEN = '10m';
export const TIME_REFRESH_TOKEN = '1d';
export const KEY_ACCESS_TOKEN = 'MMMMMMMMMMMMMMMMMMMMMMMMMBBBBBBBBBBBBB';
export const KEY_REFRESH_TOKEN = 'SSSSSSSSSSSSSSSSSSAAAAAAAAAAAAAAAAAA';
